server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: discovery-service
          uri: http://localhost:8761
          predicates:
            - Path=/eureka
          filters:
            - SetPath=/

        - id: discovery-service-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
