spring:
  application:
    name: authentication-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 0

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem

jwt:
  expirationTimeInHours: 1