server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/user_service
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: user-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

rsa:
  public-key: classpath:certs/public.pem