#server:
#  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/user_service
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: order-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka